### ISSUE TITLE
ontology-server does not work on localhost

### ISSUE THREAD

**Issue by berezovskyi** [EricssonResearch/scott-eu#1]
Due to the hardcoded 'server' section in the nginx config. Shall use a docker parameter somehow.

**Comment by berezovskyi** [comment]
All right, I knew somebody would bring a full template engine into the picture: https://tryolabs.com/blog/2015/03/26/configurable-docker-containers-for-multiple-environments/

**Comment by berezovskyi** [comment]
cc @likelion

**Comment by berezovskyi** [comment]
@konstantino I remember you used some `${}` parameter from some YAML file. I looked everywhere for it but could not find anything in this repo. Can you remind me, please?

**Comment by likelion** [comment]
This seems to be a solution:

```
# docker-compose.yml file
version: '2'

services:
  django:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - SOMETHING=foo

# Dockerfile
ARG SOMETHING
RUN echo $SOMETHING
```
