### ISSUE TITLE
Automatically detect when the controller interfaces are running

### ISSUE THREAD

**Issue by jramadeu** [EricssonResearch/scott-eu#119]
Some times due to a low frame rate on v-rep, the controller interface will take a longer time to be loaded. This cause an unexpected behaviour, as moveit search for the controller interface but the interfaces are still waiting for v-rep to be loaded. [Check it here](https://github.com/EricssonResearch/scott-eu/pull/115#issuecomment-427962751).

To solve this we need to automatically detect when the controller interfaces are running and then we spawn moveit

**Comment by berezovskyi** [comment]
Closing as wontfix; the project is finished and the repository is to be archived.
