### ISSUE TITLE
Lock master branch

### ISSUE THREAD

**Issue by berezovskyi** [EricssonResearch/scott-eu#12]
We did it already but non-masters can't accept a PR. I would like to encourage everyone to approve and merge PRs. But I wanted to make that we can't push to master but can accept pull requests. Maybe this will work better:

![image](https://user-images.githubusercontent.com/64734/28116354-13f2448e-6709-11e7-8fc0-e2863e5713ab.png)

**Comment by likelion** [comment]
Ok, I removed "Restrict who can push to this branch" checkbox. What do you see now?

**Comment by berezovskyi** [comment]
For now I see that a review is required before a merge, which is good. Can you approve #4?

**Comment by berezovskyi** [comment]
Perfect!
