### ISSUE TITLE
Getting closer to shelves

### ISSUE THREAD

**Issue by jramadeu** [EricssonResearch/scott-eu#123]
Nowadays we're using the shelves' waypoints for robot's navigation. To execute the pick-up the robot needs to be closer to the shelf. To make robot closer to the shelf, in #116, I tried to change the waypoint x coordinate from 1.61 to 1.37, but with this new coordinate the robot is not able to navigate until this position. 

I think this behaviour is due to the obstacles and robot inflation on the cost map, but I was not able to change that on turtlebot2i_navigation/config/costmap_common_params.yaml and make the robot closer to the shelf.

**Comment by albertohata** [comment]
> Nowadays we're using the shelves' waypoints for robot's navigation. To execute the pick-up the robot needs to be closer to the shelf. To make robot closer to the shelf, in #116, I tried to change the waypoint x coordinate from 1.61 to 1.37, but with this new coordinate the robot is not able to navigate until this position.
> 
> I think this behaviour is due to the obstacles and robot inflation on the cost map, but I was not able to change that on turtlebot2i_navigation/config/costmap_common_params.yaml and make the robot closer to the shelf.

Maybe it is a problem in the grid map. The existing map may not be so accurate as required and needs to be regenerated.

**Comment by albertohata** [comment]
This issue is related to the Issue #122

**Comment by albertohata** [comment]
@jramadeu I updated the map in the branch issue_122. In this map the shelves have a thinner border. Please, check if it works.

**Comment by jramadeu** [comment]
@albertohata, on issue #139 i've made some changes that partially solve this issue. 

Please take a look there, and if it's possible update this changes on branch issue_112.

**Comment by albertohata** [comment]
> @albertohata, on issue #139 i've made some changes that partially solve this issue.
> 
> Please take a look there, and if it's possible update this changes on branch issue_112.

@jramadeu I will check that. By the way, you mean issue_122 right?

**Comment by jramadeu** [comment]
Sorry. Branch issue_122.

Btw, #143 can also benefit on this.

**Comment by berezovskyi** [comment]
Closing as wontfix; the project is finished and the repository is to be archived.
