### ISSUE TITLE
Fix warehouse_turtlebot2i_v4.ttt scenario and clean up

### ISSUE THREAD

**Issue by albertohata** [EricssonResearch/scott-eu#135]
- [x] Make the `warehouse_turtlebot2i_v4.ttt` scenario run with the current ROS packages and lua scripts.
- [x] Remove GPS from the scenario.
- [x] Remove unnecessary scenarios.
- [x] Remove unnecessary lua scripts.
- [x] Move the v-rep internal scripts to the external lua scripts. 
- [x] Fix GPS module problem on `warehouse_turtlebot2i_v4.ttt`.
- [ ] Add safety scenarios (reorganize the folders as well?).

**This issue is associated to the branch issue_135.**

**Comment by berezovskyi** [comment]
Closing as wontfix; the project is finished and the repository is to be archived.
