### ISSUE TITLE
test new scene with ros

### ISSUE THREAD

**Issue by KRaizer** [EricssonResearch/scott-eu#140]
@jramadeu and @albertohata 

I've create this branch with the new "git friendlier" scene:
[https://github.com/EricssonResearch/scott-eu/tree/vrep_git_friendlier/simulation-ros/src/turtlebot2i/turtlebot2i_description/v-rep_model/warehouse_scene](https://github.com/EricssonResearch/scott-eu/tree/vrep_git_friendlier/simulation-ros/src/turtlebot2i/turtlebot2i_description/v-rep_model/warehouse_scene)

We need to test its connection with ROS

**Comment by jramadeu** [comment]
Hi, the branch vrep_git_friendlier is tested and updated to reflect your last changes @KRaizer and I erased the branch /oring/vrep_git_firendlier.

Testing the scene I notice that I'm not able to disable the cameras using `sim.setExplicitHandling(object_camera_rgb, 1) -- disable camera rgb
sim.setExplicitHandling(object_camera_depth, 1) -- disable camera depth`  

These lines are supposed to disable the camera, am I right?

**Comment by KRaizer** [comment]
Hi @jramadeu 
I'm not sure how setting to explicit handling alone would disable the vision sensor.

What the code was attempting to do was to use it as a flag to know whether or not to publish rgb and depth info to ROS. I had to change the code in sensing to actually do that though.

Important: Each robot has two separate cameras: "camera" and "camera_sr300". You have to enable/disable them individually at "camera.lua" and "camera_sr300.lua" respectively.

@albertohata and @jramadeu , what do we actually want here? Being able to fully disable the vision sensors? Or keep them enabled but handled explicitly?

**Comment by albertohata** [comment]
> Hi @jramadeu
> I'm not sure how setting to explicit handling alone would disable the vision sensor.
> 
> What the code was attempting to do was to use it as a flag to know whether or not to publish rgb and depth info to ROS. I had to change the code in sensing to actually do that though.
> 
> Important: Each robot has two separate cameras: "camera" and "camera_sr300". You have to enable/disable them individually at "camera.lua" and "camera_sr300.lua" respectively.
> 
> @albertohata and @jramadeu , what do we actually want here? Being able to fully disable the vision sensors? Or keep them enabled but handled explicitly?

@KRaizer the `setExplicitHandling` function was used to disable the sensor as mentioned in http://www.forum.coppeliarobotics.com/viewtopic.php?t=2795

**Comment by berezovskyi** [comment]
Closing as wontfix; the project is finished and the repository is to be archived.
