### ISSUE TITLE
Fix merge problem with risk_assess_fls branch

### ISSUE THREAD

**Issue by albertohata** [EricssonResearch/scott-eu#147]
There was a merge problem with the risk_assess_fls branch (c77b94039471ce997692bf05d8e21204f56d4531).

Some files were removed and should be added again:
- simulation-ros/src/turtlebot2i/turtlebot2i_safety/CMakeLists.txt
- simulation-ros/src/turtlebot2i/turtlebot2i_safety/msg/SafetyZone.msg
- simulation-ros/src/turtlebot2i/turtlebot2i_safety/package.xml

**Comment by berezovskyi** [comment]
Closing as wontfix; the project is finished and the repository is to be archived.
