### ISSUE TITLE
Test simplified turttlebot in warehouse_scene.ttt

### ISSUE THREAD

**Issue by KRaizer** [EricssonResearch/scott-eu#157]
@jramadeu and @albertohata

Could you test the simplified turttlebot in this branch for your applications before we merge into master?

https://github.com/EricssonResearch/scott-eu/tree/improve_turtlebot2i_fps

**Comment by albertohata** [comment]
> @jramadeu and @albertohata
> 
> Could you test the simplified turttlebot in this branch for your applications before we merge into master?
> 
> https://github.com/EricssonResearch/scott-eu/tree/improve_turtlebot2i_fps

@KRaizer it works! It seems faster now. Is it possible to also keep the old version, in which the robot has all the sensors equipped (eg proximity sensor, IMU)?

**Comment by berezovskyi** [comment]
Closing as wontfix; the project is finished and the repository is to be archived.
