### ISSUE TITLE
Improve the OSLC library for Prolog 

### ISSUE THREAD

**Issue by berezovskyi** [EricssonResearch/scott-eu#20]
From #17:

**Future work**

- [x] optimize `copy_resource/5` using dictionaries and make it default resource shape validator
- [x] add settings to configure which prefixes and ontologies are exposed via REST interface
- [x] implement validation of `oslc:range`, `oslc:allowedValue` and `oslc:maxSize`
- [x] implement properer exception handling and error reporting using `oslc:Error`
- [ ] resource paging
- [ ] validation of value shapes
- [ ] create API for OSLC clients in Prolog
- [ ] write a complete set of unit tests

**Bonus features**

- [ ] implement query strings for Query Capability's base URI
- [ ] authentication mechanisms (basic, OAuth, form)
- [ ] support for JSON representation of OSLC Defined Resources
- [ ] UI previews
- [ ] Delegated User Interface Dialogs

**Comment by likelion** [comment]
Moved to https://github.com/EricssonResearch/oslc_prolog/issues/1
