### ISSUE TITLE
Consider archiving the repo

### ISSUE THREAD

**Issue by berezovskyi** [EricssonResearch/scott-eu#214]
Given that SCOTT is over and we are not planning to maintain the code here mostly, shall we either archive the repo or at least disable security scanning and add a note to the README that the project is no longer maintained (the only reason is in case someone will try to open a ticket).

**Comment by berezovskyi** [comment]
@likelion @swarupmohalik @albertohata what's your thought

**Comment by albertohata** [comment]
@berezovskyi We have two master students that are still using this repo, but are intended to conclude their work on January/February. Is it possible to do that after they finishing their work?

**Comment by berezovskyi** [comment]
@albertohata what's the status?

**Comment by albertohata** [comment]
Hi @berezovskyi, we recently started using the gitlab so we can archive the repo.
