### ISSUE TITLE
To build an OSLC compliant warehousecontroller

### ISSUE THREAD

**Issue by swarupmohalik** [EricssonResearch/scott-eu#40]
Redesign the warehousecontroller to make it OSLC compliant.
Following interfaces are to be implemented.
1. 
input : MOO mission from MOO_stub, 
Output : acknowledgement to MOO_Stub, 
Output : plan request to Planning Service, set timer

2. 
input : Acknowledgement from Planning Service
output : Negative Ack/Timeout -> Negative reply to MOO_Stub
             Positive Ack -> Wait for plan

3. 
input : configuration request (from domain/problem service)
output : warehouse configuration 

4.
input : plan from Planner Service
output : Estimation Request to Estimator, 

5.
input : estimation acknowledgement from Estimator
output : negative -> Negative reply to MOO_Stub
              positive -> wait

6.
 input : Plan Estimation from Estimator, 
Output : timeout -> Negative reply to MOO_Stub
              Else -> Plan and estimator output to MOO_Stub

**Comment by berezovskyi** [comment]
So we need to remove the MOO from the picture here. Let's see.

In the grand picture, the WHC can accept the mission from WHM as text:

> MOVE 2 pairs of JEANS FROM the SHELF S1 to S2

into the mission:

```
_:sel a CountSelector ;
  count "2"^xsd:integer ;
  selector [
    a TypeSelector ;
    itemType _:Bluejeans .
    selector [
      a LocationSelector ;
      location _:shelf1 .
    ]
  ] .

_:mission a MoveGoal;
  selector _:sel ;
  destination _:shelf2 .
```

Then we must resolve the selector in the WHC and output the `PlanningRequest` to the PLS:

```
_:planreq a PlanRequest ;
  pddl:object :a ,
              :b ,
              :c ,
              :table ;
  pddl:goal [ a pddl:Or ;
              pddl:argument [ a :on ;
                              :on-x :b ;
                              :on-y :c
                            ] ,
                            [ a :on ;
                              :on-x :c ;
                              :on-y :b
                            ]
            ] .
```

>https://github.com/EricssonResearch/scott-eu/blob/master/planner_reasoner/rdf/base/pddl_example.ttl#L264
> 
> https://github.com/EricssonResearch/scott-eu/blob/master/planner_reasoner/rdf/base/pddl_example.ttl#L311

And then we push it over the MQTT to the channel that the PLS listens on.

**Comment by swarupmohalik** [comment]
So does it mean that WHC is serving the mission RDF now?

Since no one else (except possibly an analytics component in the future) is using the mission,
it could be directly consumed by the WHC to produce the problem file for the plan object for PLC.

Or, will it be modular if we have an adaptor for the WHM GUI serving the mission RDF?

**Comment by berezovskyi** [comment]
I am actually thinking to make a static GUI webapp (on webpack, bootstrap and Vue) for the WHM separately and have it make AJAX calls to the REST API of the WHC.

WHC does not strictly have to serve the mission RDF, but I think it should (just to show all missions in the UI).

**Comment by swarupmohalik** [comment]
I like the idea of remembering the missions - the history will definitely be useful later.
The only question remains who is going to serve it. Let's discuss this directly.
