### ISSUE TITLE
Order preservation in and of effect

### ISSUE THREAD

**Issue by likelion** [EricssonResearch/scott-eu#47]
There is a suspicion that PDDL implicitly assumes preservation of order of arguments of `and` in the effect specification. In fact, it makes sense, since in general it is allowed to have dependent fluents, i.e. those that compute values based on the result of previous fluents, so order matters. However, current implementation of PDDL generator does not preserve order.

**Comment by likelion** [comment]
The solution would be to add `sh:order` property to `pddl:argument` objects of `pddl:and` in effect.

**Comment by swarupmohalik** [comment]
I am checking the semantics of PDDL2.1 There seems to be some restrictions on how the fluents may be specified in the effects. Will update soon. However, having the order will not harm.

**Comment by swarupmohalik** [comment]
There are certain restrictions mentioned in PDDL2.1 on the fluent operations (See section 7 of the JAIR paper (long&Fox, 2003), specifically, definitions 7 and 8). This is to ensure that the assignment operations commute. 
For example, 
1. multiple assignments to same primitive numerical expression is not allowed.
2. There cannot be a mix of operations (increase, decrease, scale-up, scale-down).
3. Still allows repeat of same operation i.e. (increase (volt a) 1)(increase (volt a) 2)

Implication: 
**For cases where there are at most 1 assignment to a function, e.g.**

(increase (volt a) 1)(decrease (charge b)(volt a)) in the effect would refer to the current 
value of (volt a) in both the expressions (which is the value in the current state and not after the 
action application)

**Hence, order of the operations is not important.**

**Case: when multiple assignments are there for single function, e.g.**
(increase (volt a) 1)(increase (volt a) (+2 (volt a))?
Operations will not commute.
Checking this with FF/Optic. 
**But this case is not natural, if one wanted to update, one could write a single update expression.**

**Comment by swarupmohalik** [comment]
FF supports increase/decrease by a constant amount. Ex : (increase (voltage b) 2)
FF supports repeated numeric fluents which may be a mix of increase/decrease : the net effect is the total sum. 

Optic does not support repeated numeric fluents.
But it supports non-constant assignments e.g (increase (cost)(rate))
The r-values (here, rate) take the value from the current state and not from
the assignments before it. This validates the standard.
So if cost = 10, rate = 20,
effect - (increase (cost) 5)(increase (rate)(cost))
then after the action: cost = 10 + 5 = 15
                                   rate = 20 + 10 (note, not 15) = 30

**Comment by likelion** [comment]
@swarupmohalik So, shall we say that the order of arguments of `and` is not important in effect?

**Comment by swarupmohalik** [comment]
@likelion Yes, order of arguments in And is not necessary in effect.

**Comment by likelion** [comment]
It seems that no reimplementation is required at the moment, I'm closing this issue.
