### ISSUE TITLE
Estimator

### ISSUE THREAD

**Issue by swarupmohalik** [EricssonResearch/scott-eu#58]
The estimator takes a plan from the Warehouse Controller and returns (1) whether the plan is feasible or no, (2) safety level of the plan.

1. First, we have a simple, static estimator which uses earlier simulated data to compute the values.
2. Second, the results will be computed through simulation on ROS during the operation time

**Comment by berezovskyi** [comment]
I just merged the PR with the static estimator for §1 (#59).

**Comment by berezovskyi** [comment]
wontfix
