### ISSUE TITLE
DomainShape/action property has no range

### ISSUE THREAD

**Issue by berezovskyi** [EricssonResearch/scott-eu#65]
I thought the `action` property of the `DomainShape` would have `Action` class as an `oslc:range`. Is there a reason why is it not the case?

cc @jadelkhoury (just FYI)

**Comment by berezovskyi** [comment]
For your convenience:

```turtle
:Action
  a rdfs:Class ;
  rdfs:subClassOf :MetaClass ;
  rdfs:subClassOf :Parameterizable .

:Domain
  a rdfs:Class .

:DomainShape
  a oslc:ResourceShape ;
  oslc:describes :Domain ;
  dcterms:description "A planning domain."^^rdf:XMLLiteral ;
  oslc:property # many properties omitted,
                [ a oslc:Property ;
                  dcterms:description "Domain actions."^^rdf:XMLLiteral ;
                  oslc:propertyDefinition :action ;
                  oslc:name "action"^^xsd:string ;
                  oslc:occurs oslc:Zero-or-many ;
                  oslc:valueType oslc:LocalResource
                ] .

:ActionShape
  a oslc:ResourceShape ;
  dcterms:description "An action has parameter, precondition and effect."^^rdf:XMLLiteral ;
  oslc:property [ a oslc:Property ;
                  dcterms:description "Action name."^^rdf:XMLLiteral ;
                  oslc:propertyDefinition rdfs:label ;
                  oslc:name "label"^^xsd:string ;
                  oslc:occurs oslc:Exactly-one ;
                  oslc:valueType xsd:string
                ] ,
                [ a oslc:Property ;
                  dcterms:description "Action parameters."^^rdf:XMLLiteral ;
                  oslc:propertyDefinition :parameter ;
                  oslc:name "parameter"^^xsd:string ;
                  oslc:occurs oslc:Zero-or-many ;
                  oslc:valueType oslc:LocalResource ;
                  oslc:range :Parameter
                ] ,
                [ a oslc:Property ;
                  dcterms:description "Action precondition that must be fulfilled to enable it."^^rdf:XMLLiteral ;
                  oslc:propertyDefinition :precondition ;
                  oslc:name "precondition"^^xsd:string ;
                  oslc:occurs oslc:Exactly-one ;
                  oslc:valueType oslc:LocalResource
                ] ,
                [ a oslc:Property ;
                  dcterms:description "Action effect describing state modification."^^rdf:XMLLiteral ;
                  oslc:propertyDefinition :effect ;
                  oslc:name "effect"^^xsd:string ;
                  oslc:occurs oslc:Exactly-one ;
                  oslc:valueType oslc:LocalResource
                ] .
```

**Comment by likelion** [comment]
I think it boils down to the discussion about whether `oslc:range` can specify a superclass of allowed objects. If you look at the `pddl_example.ttl`, there is a `:move` action which is a subclass of `pddl:Action`, in order to check one has to do inferencing over `rdfs:subClassOf` relation. See comment in `oslc_prolog/lib/oscl_shape.pl` line 143.

**Comment by kicacacko** [comment]
Sorry for my ignorance, but is this related to the fact that the Action is a Meta-class (users create sub classes of this class), whereas Parameter is a PDDL class

**Comment by kicacacko** [comment]
Exectly, Leo was faster:)

**Comment by berezovskyi** [comment]
@jadelkhoury & jamsden, let me CC you in this discussion :)

Thanks @likelion @eanevul, makes sense, at least from the practical standpoint. But I think it would be totally legit to require a property to be an `Action`, while we pass it an `AdvancedAction`, because `AdvancedAction` _is a_ `Action`. So I am pretty sure OSLC allows RDF subclass/subproperty reasoning. @jadelkhoury or @jamsden can correct me if I am wrong.

@jadelkhoury, do you think there is a way to define a REST service capability in Lyo Designer that would expect an Action (eg Creation Factory) but will work well when supplied with an instance of `AdvancedAction` via POST?

**Comment by berezovskyi** [comment]
Just had a call with Jad and discussed it:

Lyo will not actually do any checks on the incoming resource against its shape. The zero-or-many links are represented via a `HashSet<Link>` and there is no further check in the code if the `Link` instance points to an instance of the right class save do any class hierarchy reasoning. There are two exceptions to the case:

1. If the property is defined with `LocalResource` value type. But there may be a workaround in the `JenaModelHelper` to switch between the source of unmarshalling info: whether to read OSLC shape annotations or use something else. Need to look up in the source code.

2. When the https://github.com/eclipse/lyo-validation library is hooked up to perform actual validation (not officially released yet).

In regard whether it is legit from the spec point of view, we need Jim's opinion. Me and Jad think its okay. Here is a recap:

---

 Let's _assume_ that there is such a shape:

```turtle
:DomainShape
  a oslc:ResourceShape ;
  oslc:describes :Domain ;
  dcterms:description "A planning domain."^^rdf:XMLLiteral ;
  oslc:property # many properties omitted,
                [ a oslc:Property ;
                  dcterms:description "Domain actions."^^rdf:XMLLiteral ;
                  oslc:propertyDefinition :action ;
                  oslc:name "action"^^xsd:string ;
                  oslc:occurs oslc:Zero-or-many ;
                  oslc:valueType oslc:Resource;
                  oslc:range :Action
                ] .

:Action
  a rdfs:Class ;
  rdfs:subClassOf :MetaClass ;
  rdfs:subClassOf :Parameterizable .

:MoveAction
  a rdfs:Class ;
  rdfs:subClassOf :Action .
```

The question is: does the following resource conform to the shape above?

```turtle

:action1 a :MoveAction .

:domain1 a :Domain .
:domain1 action :action1 .  
```

**Comment by jamsden** [comment]
From the OSLC specifications point of view, there are no domain and range properties specified in the ongologies. This is intentional, allowing for flexible links. However the OSLC specifications also specify ResourceShapes that constrain their vocabularies for OSLC integration purposes. In this case, the target of links might be constrained by oslc:range constraints. If so, then these constraints should be validated on POST and PUT operations, and perhaps supported by the applicable setter methods in the Java implementations.

The example above does look like it conforms to the constraints since :action is also an Action.

**Comment by berezovskyi** [comment]
Closing out due to the explanation from Jim.
