### ISSUE TITLE
Update the V-REP ROS lib once VREP bindings are relicensed under new BSD license 

### ISSUE THREAD

**Issue by berezovskyi** [EricssonResearch/scott-eu#76]
See https://github.com/CoppeliaRobotics/remoteApiBindings/issues/2

**Comment by berezovskyi** [comment]
The original issue is closed, now we got to update the ROS package: https://github.com/CoppeliaRobotics/v_repExtRosInterface/blob/master/license.txt

**Comment by berezovskyi** [comment]
I think we were also planning to use ROS Bridge? I filed an issue, we will see if we will be able to use it: https://github.com/lagadic/vrep_ros_bridge/issues/67

**Comment by albertohata** [comment]
Not ROS Bridge, but V-REP ROS Interface. It has BSD v2.0 license: https://github.com/CoppeliaRobotics/v_repExtRosInterface/blob/master/license.txt

**Comment by berezovskyi** [comment]
cool! the BSD license was change due to my request, so you have to make sure you update the code in the PR from the repo you linked to now.

**Comment by albertohata** [comment]
One thing that remembered is that the V-REP simulator is GPL. Is this a problem to us? We use the V-REP simulator just as a tool. http://www.coppeliarobotics.com/helpFiles/en/licensing.htm

**Comment by berezovskyi** [comment]
no, we don't link to V-REP itself

**Comment by berezovskyi** [comment]
Closing this one, and will discuss the GPL in our repo in #73
