### ISSUE TITLE
SLAM in ROS?

### ISSUE THREAD

**Issue by berezovskyi** [EricssonResearch/scott-eu#77]
I was told about http://wiki.ros.org/turtlebot_navigation/Tutorials/Build%20a%20map%20with%20SLAM in the conversation with a colleague. Are we making use of it? Are we aware it exists?

**Comment by albertohata** [comment]
Yes, we are using the gmapping to create the grid map of the environment. The path planning is already using the map created by gmapping.

**Comment by berezovskyi** [comment]
thank you!
