### ISSUE TITLE
V-REP player 3.5.0 does not start on the Debian 8 version supported by ROS Kinetic

### ISSUE THREAD

**Issue by berezovskyi** [EricssonResearch/scott-eu#84]
V-REP requires Glibc that comes with GCC 5.1, but Debian Jessie 8.10 (supported by ROS Kinetic) does not ship with it.

What were you SW versions of the OS (`lsb_release -a` to find out), GLibc, GCC, V-REP?

**Comment by berezovskyi** [comment]
For now I fell back to V-REP player 3.4.0

**Comment by berezovskyi** [comment]
I got everything to compile and run but the empire struck back in the logs of V-REP:

```
this plugin requires at least V-REP 3.4.0 rev9
Plugin 'RosInterface': load failed (failed initialization).
```

**Comment by berezovskyi** [comment]
For some reason, the 3.4.0 available from the website is rev. 1.

**Comment by berezovskyi** [comment]
I guess I will either have to use Ubuntu or be dangerous and try dist-upgrading my Debian 💣

**Comment by berezovskyi** [comment]
Debian Stretch does not sound so bad with Kinetic... http://sar-lab.net/teaching/ros-kinetic-on-raspbian-stretch-for-raspberry-pi-3/

**Comment by berezovskyi** [comment]
So, Stretch did not really work nice with my hacks... Going for Ubuntu 16.04.4 LTS (Xenial Xerus)

**Comment by berezovskyi** [comment]
So I got

```
Plugin 'RemoteApi': loading...
Starting a remote API server on port 19997
```

But I think we need to clearly document that ROS & VREP combo only works for Ubuntu & VREP PRO & VREP >= 3.5.0

**Comment by jramadeu** [comment]
Seems to be good practice to put that on the documentation. Why are you using VREP Player?

**Comment by albertohata** [comment]
Thanks for the suggestion. I included additional instructions in the readme. However, there are some 3.5.0 versions that has problems with the remote API or with the ros interface. If you keep facing problems, try different V-REP versions.

**Comment by berezovskyi** [comment]
@jramadeu I wanted to see if I can create a VM to share with others and using Player seemed best.
