### ISSUE TITLE
V-REP player is not supported 

### ISSUE THREAD

**Issue by berezovskyi** [EricssonResearch/scott-eu#85]
https://github.com/EricssonResearch/scott-eu/blob/simulation-ros/simulation-ros/src/vrep_ros_interface/cmake/modules/FindVREP.cmake#L19 requires the `programming/` folder to exist, which is missing on the V-REP installations.

**Comment by jramadeu** [comment]
This is odd. I downloaded the [linux version](http://www.coppeliarobotics.com/downloads.html) and it has the programming folder. If you're using the V-REP Player instead, don't do this. Stick to the V-REP PRO EDU.

**Comment by albertohata** [comment]
I included instruction in the readme to use the PRO or PRO edu versions. We didn't try to use the Player version yet.

**Comment by berezovskyi** [comment]
I was just thinking to use Player in a VM if it is lighter. And because instructions suggested so, I think. But thanks @albertohata for the update.
