### ISSUE TITLE
Remove Leshan from the sandbox

### ISSUE THREAD

**Issue by berezovskyi** [EricssonResearch/scott-eu#95]

**Comment by berezovskyi** [comment]
@likelion @albertohata @bluelancer what do you think, should we still remove it?

cc @rafiainam

**Comment by albertohata** [comment]
> @likelion @albertohata @bluelancer what do you think, should we still remove it?
> 
> cc @rafiainam

Hi @berezovskyi. For our side, it won't affect anything if removed.

**Comment by berezovskyi** [comment]
I kept it under https://github.com/EricssonResearch/scott-eu/tree/master/misc/ELIoT
